import { Button } from "@mui/material";
import { motion, useViewportScroll } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Hero from "../components/Homepage/Hero";
import Layout from "../components/Layout/Layout";
export default function Home() {
  const router = useRouter();
  return (
    <Layout>
      <motion.div
        initial={{ x: 300, opacity: 0 }}
        animate={{ x: 0, opacity: 1 }}
        exit={{ x: -300, opacity: 0 }}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Hero />
      </motion.div>
    </Layout>
  );
}
